all: client server

clean:
	rm -rf client_app
	rm -rf server_app
	rm -rf attack_app


client:
	g++ -o client_app ./client.cpp

server:
	g++ -o server_app ./server.cpp

attack:
	g++ -o attack_app ./attack.cpp